language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache:
  directories:
    - stripe-mock

env:
  global:
    # N.B. Whenever this is updated, please update `tests/common.rs` as well
    - STRIPE_MOCK_VERSION=0.90.0

before_install:
  # Unpack and start stripe-mock so that the test suite can talk to it
  - |
    if [ ! -d "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}" ]; then
      mkdir -p stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/
      curl -L "https://github.com/stripe/stripe-mock/releases/download/v${STRIPE_MOCK_VERSION}/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -o "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz"
      tar -zxf "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -C "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/"
    fi
  # - |
  #   stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/stripe-mock -strict-version-check > /dev/null &
  #   STRIPE_MOCK_PID=$!
  # - export PATH="${PATH}:${PWD}/stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}"

script:
  - rustup component add rustfmt
  - cargo fmt -- --check

  # Check minimal features "runtime-blocking"
  - cargo build --verbose --workspace --exclude binary_size --no-default-features --features runtime-blocking

  # Check "runtime-blocking"
  - cargo build --verbose --workspace --exclude binary_size --no-default-features --features "runtime-blocking full webhook-events"
  - cargo test --verbose --workspace --exclude binary_size --no-default-features --features "runtime-blocking full webhook-events"

  # Check "runtime-blocking-rustls"
  - cargo build --verbose --workspace --exclude binary_size --no-default-features --features "runtime-blocking-rustls full webhook-events"
  - cargo test --verbose --workspace --exclude binary_size --no-default-features --features "runtime-blocking-rustls full webhook-events"

  # Check "runtime-tokio-hyper"
  - cargo build --verbose --workspace --exclude binary_size --features runtime-tokio-hyper
  - cargo test --verbose --example async_create_charge --features runtime-tokio-hyper

  # Check "runtime-tokio-hyper-rustls"
  - cargo build --verbose --workspace --exclude binary_size --features runtime-tokio-hyper-rustls
  - cargo test --verbose --example async_create_charge --features runtime-tokio-hyper-rustls

  # Check "runtime-async-std-surf"
  - cargo build --verbose --workspace --exclude binary_size --features runtime-async-std-surf
  - cargo test --verbose --example async_create_charge --features runtime-async-std-surf
