[package]
name = "stripe-rust" # b.c. stripe and stripe-rs were already taken
version = "0.4.5"
description = "API bindings for the Stripe v1 HTTP API"
authors = ["Kevin Stenerson <kevin@rapiditynetworks.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rapiditynetworks/stripe-rs"
documentation = "https://docs.rs/stripe-rust"
keywords = ["stripe", "v1", "api"]
categories = ["api-bindings"]

[badges]
travis-ci = {repository = "rapiditynetworks/stripe-rs"}

[features]
default = ["with-rustls"]
with-rustls = ["hyper-rustls"]
with-openssl = ["hyper-openssl"]

[lib]
name = "stripe"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
hmac = "^0.1"
hyper = "^0.10"
hyper-rustls = { version = "^0.6", optional = true }
hyper-openssl = { version = "^0.2", optional = true }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
serde_qs = "^0.2"
sha2 = "^0.5"
