[package]
name = "stripe-rust" # b.c. stripe and stripe-rs were already taken
version = "0.2.0"
description = "API bindings for the Stripe v1 HTTP API"
authors = ["Kevin Stenerson <kevin@rapiditynetworks.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rapiditynetworks/stripe-rust"
homepage = "https://github.com/rapiditynetworks/stripe-rust"
keywords = ["stripe", "v1", "api"]
categories = ["api-bindings"]

[lib]
name = "stripe"

[dependencies]
hyper = "0.10"
hyper-openssl = "0.2"
serde = "^0.9"
serde_derive = "^0.9"
serde_json = "^0.9"
serde_qs = "0.0.1"
