[package]
name = "stripe-rust" # b.c. stripe and stripe-rs were already taken
version = "0.4.0-dev"
description = "API bindings for the Stripe v1 HTTP API"
authors = ["Kevin Stenerson <kevin@rapiditynetworks.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rapiditynetworks/stripe-rs"
documentation = "https://docs.rs/stripe-rust"
keywords = ["stripe", "v1", "api"]
categories = ["api-bindings"]

[lib]
name = "stripe"

[dependencies]
hyper = "^0.10"
hyper-rustls = "^0.6"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
serde_qs = "^0.2"
