[package]
name = "stripe-rust" # b.c. stripe and stripe-rs were already taken
version = "0.1.1"
authors = ["Kevin Stenerson <kevin@rapiditynetworks.com>"]

[lib]
name = "stripe"

[dependencies]
hyper = "0.10"
hyper-openssl = "0.2"
serde = "^0.9"
serde_derive = "^0.9"
serde_json = "^0.9"
serde_urlencoded = "0.4.2"
