[package]
name = "stripe-openapi-codegen"
version = "0.1.0"
authors = ["Kevin Stenerson <kstenerson@developers.wyyerd.com>"]
edition = "2018"

[dependencies]
heck = "0.3"
lazy_static = "1"
reqwest = "0.10.0-alpha.2"
regex = "1"
serde_json = "1"
