##
## Example
##

# [[benchmark]]
# commit = "d3be971826d775e7506352f2e63c59cd2a354525"
# profile = "debug"
# features = ["full"]
# hardware = "MacBook Air (13-inch, 2018)"
# time = { debug = "_m __s" } # as reported by `cargo build`
# size = { release = "___M" } # size of `.rlib`

##
## Version: 0.12.0-alpha.1
##

[[benchmark]]
commit = "ce0ec0d2959f846808026c14f8ebbe8c26818c85"
hardware = "MacBook Air (13-inch, 2018)"
features = []
time = { release = "10m 01s" }
size = { release = "43M", debug = "87M" }

[[benchmark]]
commit = "d3be971826d775e7506352f2e63c59cd2a354525"
hardware = "MacBook Air (13-inch, 2018)"
features = ["full"]
time = { release = "12m 18s", debug = "4m 39s" }
size = { release = "92M", debug = "207M"}
