name: OpenAPI
on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:
jobs:
  update-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: regenerate openapi
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: openapi-install
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Bump OpenAPI version
          title: Bump OpenAPI version
          body: This PR pulls in the latest openapi changes from github.
          branch: openapi
          branch-suffix: timestamp
          assignees: arlyon
